# Generated by Django 6.0.6 on 2026-06-24 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('HOME_ADMIN', 'Home Admin'), ('HOST_COORD', 'Host Coordinator')], default='STUDENT', max_length=20)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text="Student's current GPA on a 4.0 scale.", max_digits=3, null=True)),
                ('major', models.CharField(blank=True, help_text="Student's declared major at home institution.", max_length=200, null=True)),
                ('home_institution', models.CharField(blank=True, help_text="Name of the student's home university.", max_length=300, null=True)),
                ('enrollment_year', models.PositiveSmallIntegerField(blank=True, help_text='Academic year the student enrolled (e.g. 2022).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'gs_users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
