# Generated by Django 6.0.6 on 2026-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate Student'), ('POSTGRADUATE', 'Postgraduate Student'), ('HIGH_SCHOOL', 'High School Student'), ('INDEPENDENT', 'Independent Learner')], default='UNDERGRADUATE', help_text='Type of student — determines which eligibility rules apply.', max_length=20, null=True),
        ),
    ]
