# Generated by Django 6.0.6 on 2026-06-09 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Academic year the student enrolled (e.g. 2022).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Student's current GPA on a 4.0 scale.", max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_institution',
            field=models.CharField(blank=True, help_text="Name of the student's home university.", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, help_text="Student's declared major at home institution.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('HOME_ADMIN', 'Home Admin'), ('HOST_COORD', 'Host Coordinator')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='user',
            table='gs_users',
        ),
    ]
