# Generated by Django 6.0.6 on 2026-07-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('users', '0002_user_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host_university',
            field=models.ForeignKey(blank=True, help_text='The university this coordinator manages (only for HOST_COORD role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_coordinators', to='universities.university'),
        ),
    ]
