# Generated by Django 6.0.6 on 2026-07-13 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_host_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this user has been verified by a Super Admin. Students are auto-verified.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this user was verified.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Super Admin who verified this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('HOME_ADMIN', 'Home Admin'), ('HOST_COORD', 'Host Coordinator'), ('SUPER_ADMIN', 'Super Admin')], default='STUDENT', max_length=20),
        ),
    ]
