# Generated by Django 6.0.6 on 2026-06-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPLIANCE_PHASE', 'Compliance Phase'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('gpa_at_submission', models.DecimalField(blank=True, decimal_places=2, help_text="Student's GPA at the time this application was submitted.", max_digits=3, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Mandatory explanation populated by admin when status is set to REJECTED.')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes visible only to HOME_ADMIN and HOST_COORD.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='universities.university')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.program')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin or coordinator currently responsible for this application.', limit_choices_to={'role__in': ['HOME_ADMIN', 'HOST_COORD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'gs_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_course_code', models.CharField(help_text="Course code as listed by the host university (e.g. 'CS-401').", max_length=50)),
                ('host_course_name', models.CharField(max_length=300)),
                ('host_credits', models.DecimalField(decimal_places=2, help_text='Number of credits awarded by the host institution.', max_digits=5)),
                ('host_grade', models.CharField(blank=True, default='', help_text="Grade received at the host institution (e.g. 'A', 'B+', '85').", max_length=10)),
                ('home_equivalent_course_code', models.CharField(blank=True, default='', help_text='Corresponding home institution course code this maps to.', max_length=50)),
                ('home_equivalent_course_name', models.CharField(blank=True, default='', max_length=300)),
                ('home_credits_awarded', models.DecimalField(blank=True, decimal_places=2, help_text='Credits officially recognized by the home institution after transfer approval.', max_digits=5, null=True)),
                ('transfer_status', models.CharField(choices=[('PENDING', 'Pending Home Institution Review'), ('APPROVED', 'Approved for Transfer'), ('DENIED', 'Denied — Does Not Meet Requirements'), ('PARTIAL', 'Partial Credit Approved')], db_index=True, default='PENDING', max_length=10)),
                ('denial_reason', models.TextField(blank=True, default='', help_text='Required if transfer_status is DENIED or PARTIAL.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer_logs', to='applications.application')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_credit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transfer Log',
                'verbose_name_plural': 'Credit Transfer Logs',
                'db_table': 'gs_credit_transfer_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT_SCAN', 'Passport Scan'), ('VISA_COPY', 'Visa Copy'), ('BANK_STATEMENT', 'Bank Statement'), ('ACADEMIC_TRANSCRIPT', 'Academic Transcript'), ('LANGUAGE_TEST_RESULT', 'Language Test Result'), ('REFERENCE_LETTER', 'Reference Letter'), ('PERSONAL_STATEMENT', 'Personal Statement'), ('MEDICAL_CLEARANCE', 'Medical Clearance'), ('INSURANCE_PROOF', 'Proof of Health Insurance'), ('HOUSING_CONFIRMATION', 'Housing Confirmation Letter')], max_length=30)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory documents block approval if not submitted and approved.')),
                ('file_attachment', models.FileField(blank=True, help_text='Uploaded by the student. Null until student uploads.', null=True, upload_to='documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending — Awaiting Student Upload'), ('AWAITING_REVIEW', 'Awaiting Admin Review'), ('APPROVED', 'Approved'), ('ACTION_REQUIRED', 'Action Required — Resubmit')], db_index=True, default='PENDING', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='', help_text='Required when verification_status is ACTION_REQUIRED. Explains exactly what the student must correct and resubmit.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='applications.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Checklist Item',
                'verbose_name_plural': 'Document Checklist Items',
                'db_table': 'gs_document_checklist',
                'ordering': ['application', 'document_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'COMPLIANCE_PHASE'])), fields=('student', 'destination_university', 'program'), name='unique_active_application_per_student_university_program'),
        ),
        migrations.AlterUniqueTogether(
            name='credittransferlog',
            unique_together={('application', 'host_course_code')},
        ),
        migrations.AlterUniqueTogether(
            name='documentchecklist',
            unique_together={('application', 'document_type')},
        ),
    ]
