# Generated by Django 6.0.6 on 2026-07-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_active_application_per_student_university_program',
        ),
    ]
