# Generated by Django 6.0.6 on 2026-06-19 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('minimum_gpa', models.DecimalField(decimal_places=2, help_text='Minimum GPA (out of 4.0) required for application.', max_digits=3)),
                ('primary_language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Mandarin', 'Mandarin'), ('Arabic', 'Arabic'), ('Portuguese', 'Portuguese'), ('Other', 'Other')], default='English', max_length=50)),
                ('language_test_required', models.BooleanField(default=False, help_text='Whether an official language test (IELTS/TOEFL/DELF) is required.')),
                ('minimum_language_score', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum score on language proficiency test if required.', max_digits=5, null=True)),
                ('max_international_students', models.PositiveIntegerField(blank=True, help_text='Annual intake cap for international students. Null = no published cap.', null=True)),
                ('travel_advisory_level', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NORMAL', 'Normal — No advisory'), ('LEVEL_1', 'Level 1 — Exercise Normal Precautions'), ('LEVEL_2', 'Level 2 — Exercise Increased Caution'), ('LEVEL_3', 'Level 3 — Reconsider Travel'), ('LEVEL_4', 'Level 4 — Do Not Travel')], default='UNKNOWN', help_text='Populated automatically by the travel safety scraper.', max_length=20)),
                ('advisory_last_updated', models.DateTimeField(blank=True, help_text='Timestamp of the last successful scraper run for this university.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'gs_universities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('degree_level', models.CharField(choices=[('BACHELOR', "Bachelor's"), ('MASTER', "Master's"), ('PHD', 'PhD'), ('EXCHANGE', 'Exchange / Non-degree'), ('DIPLOMA', 'Diploma')], max_length=20)),
                ('duration_semesters', models.PositiveSmallIntegerField(help_text='Length of the program in semesters.')),
                ('tuition_per_semester_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credits_transferable', models.BooleanField(default=True, help_text='Whether credits earned are eligible for transfer back to the home institution.')),
                ('application_deadline', models.DateField(blank=True, help_text='Next upcoming application deadline for this program.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'gs_programs',
                'ordering': ['university', 'name'],
                'unique_together': {('university', 'name', 'degree_level')},
            },
        ),
    ]
