# Generated by Django 6.0.6 on 2026-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, help_text='University logo or campus image', null=True, upload_to='universities/'),
        ),
    ]
