# Generated by Django 6.0.5 on 2026-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of the program, benefits, and what students can expect.'),
        ),
    ]
