# Generated by Django 6.0.5 on 2026-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default='t=True', help_text='Brief description of the program, benefits, and what students can expect.'),
        ),
    ]
