# Generated by Django 6.0.6 on 2026-07-05 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_UNDER_REVIEW', 'Application Under Review'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_ACTION_REQUIRED', 'Document Action Required'), ('CREDIT_TRANSFER_APPROVED', 'Credit Transfer Approved'), ('MESSAGE', 'General Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('related_application_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gs_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
